# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdescription',
            name='mod_date',
            field=models.DateField(verbose_name=b'date last modified'),
        ),
        migrations.AlterField(
            model_name='textdescription',
            name='pub_date',
            field=models.DateField(verbose_name=b'date published'),
        ),
    ]
