# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160329_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textdescription',
            name='pub_date',
        ),
    ]
