# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_textdescription_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('text', models.TextField(verbose_name=b'blog text')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='textdescription',
            name='mod_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
