# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_blogpost_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_image',
            field=models.FilePathField(default=b'/Users/Tom/Downloads/'),
        ),
    ]
