# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20160407_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subject',
            field=models.CharField(blank=True, choices=[(b'TEST', b'Test')], max_length=250, null=True),
        ),
    ]
