# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20160413_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_image',
            field=models.ImageField(null=True, upload_to=b'blog/images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateField(null=True),
        ),
    ]
