# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20160415_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='subject',
            field=models.CharField(choices=[(b'TEST', b'Test')], max_length=250, null=True),
        ),
    ]
